# Builds a full-scale image of 302.57 MB
FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json .

RUN npm i --omit=dev

COPY . .

RUN rm Dockerfile*
RUN rm package*

EXPOSE 3000

CMD ["node", "server.js"]